### ISSUE TITLE
Available Globally doesn't default to true (but looks like it should)

### ISSUE THREAD

**Issue by Hels666** [dnadesign/silverstripe-elemental-virtual#20]
The code for BaseElementExtension.php contains:

`private static $db = [
        'AvailableGlobally' => 'Boolean(1)'
    ];`

which suggests that all elements should be set to Available Globally by default, but they are not.

Currently, it can be changed by yml file (although that isn't explained in the readme) but if they should be Available Globally by default then adding this works:

`private static $defaults = [
        'AvailableGlobally' => 1
  ];`

**Comment by robbieaverill** [comment]
I assume you're correct - would you like to make a pull request to fix this?

**Comment by Hels666** [comment]
I have done the pull request - it's #21

**Comment by wilr** [comment]
You need to opt into this via the config API.

```
DNADesign\Elemental\Models\BaseElement:
  default_global_elements: 1
```
