### ISSUE TITLE
New Version Doesn't bootstrap UI properly

### ISSUE THREAD

**Issue by JessChampion** [dnadesign/silverstripe-elemental-virtual#27]
Heya,

I just tried installing 1.2.0 in an existing elemental setup and found it wasn't adding the 'link existing' box to the elemental area anymore.
Downgrading to 1.1 and the box is back. I'm guessing this is either a bug or the install instructions need updating.

**Comment by wilr** [comment]
Tested on latest and confirmed this is fixed.
