### ISSUE TITLE
Saving a virtual element clears its selection

### ISSUE THREAD

**Issue by jules0x** [dnadesign/silverstripe-elemental-virtual#31]
If I go into a virtual element holding a listicle item, and then edit any settings of the virtual element (e.g. background colour), then listicle item gets unlinked from the virtual element.

In the screenshot, I've modified a static to show the item linked in the autocomplete field... it is empty despite there being a linked element.
This allows autocomplete to link to a new element, but clears the current element if the virtual is saved. Not ideal if for example the virtual has additional fields added by extension and one of these needs updating...
![image](https://user-images.githubusercontent.com/8979741/68244900-b15e9f80-007a-11ea-9853-50b8c09395ca.png)

**Comment by wilr** [comment]
Closing as no longer an issue with the TagField implementation
