### ISSUE TITLE
Replace virtual block svg with font-icon to be consistent with CMS pattern library

### ISSUE THREAD

**Issue by sachajudd** [dnadesign/silverstripe-elemental-virtual#33]
I've added `block-link` to our core font set which I suggest should be replaced with the current svg to be consistent with our CMS pattern library.
See https://github.com/silverstripe/silverstripe-admin/pull/1003 for the new block-icon set.

Current:
![image](https://user-images.githubusercontent.com/24258161/81998841-92833a80-96a7-11ea-9157-26886a0ea16e.png)

Replacement (in context with `font-icon-block-` icons):
![image](https://user-images.githubusercontent.com/24258161/81999877-ab411f80-96aa-11ea-83e9-de1ca6cba817.png)

Let me know what you think! 🙂

**Comment by lerni** [comment]
@sachajudd looks alot like https://github.com/dnadesign/silverstripe-elemental-virtual/pull/32

**Comment by sachajudd** [comment]
Cool thanks for that @lerni, I've just linked the two together and left a review.

**Comment by lerni** [comment]
@sachajudd - it's merged but not released yet. Can this be closed anyway?
