### ISSUE TITLE
Better visual GridField selector for “link existing” UI

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental-virtual#5]
@pitchandtone commented on [Fri Jul 14 2017](https://github.com/dnadesign/silverstripe-elemental/issues/95)

Refer to content blocks module for modal UI which I believe is better

---

@pitchandtone commented on [Wed Aug 02 2017](https://github.com/dnadesign/silverstripe-elemental/issues/95#issuecomment-319633446)

Need to use GridFieldAddExistingSearchHandler and extend to do add() like ElementalGridFieldAddExistingAutocompleter handles this currently.

---

@robbieaverill commented on [Wed Oct 25 2017](https://github.com/dnadesign/silverstripe-elemental/issues/95#issuecomment-339215997)

I think we could probably move this issue to github.com/dnadesign/silverstripe-elemental-virtual now

**Comment by wilr** [comment]
@robbieaverill Have updated it in the short term to use Tractor Cows autocomplete field which I think works well. However i would love to be able to use that form field inline (which doesn't current work) perhaps get that solved and we'll be sweet.

**Comment by micschk** [comment]
I suggest using the Tagfield for this instead, one of the few fields which have been '[modernised](https://github.com/silverstripe/silverstripe-framework/issues/6689)' and actually (sort of) works through react so will allow [inline editing](https://github.com/dnadesign/silverstripe-elemental-virtual/issues/48) as well. PR coming up...

**Comment by wilr** [comment]
Closing as done.
