### ISSUE TITLE
Bring back (block type) in linked element selection

### ISSUE THREAD

**Issue by jalamanderman** [dnadesign/silverstripe-elemental-virtual#58]
Since the introduction of tag field. It appears the block type and ID is no longer appended in the dropdown. 
This was a rather useful feature for content editors where different block types share the same name. 

Is is possible to bring it back?

<img width="653" alt="Screenshot 2023-10-10 at 11 41 48 AM" src="https://github.com/dnadesign/silverstripe-elemental-virtual/assets/33302399/38dad060-b2be-4d59-823b-2e05d54bedd5">

**Comment by wilr** [comment]
@jalamanderman This is now managed via an extension hook `updateVirtualLinkedSummary`. Type and ID is included already in the latest release but if you want to tailor it here is the hook

https://github.com/dnadesign/silverstripe-elemental-virtual/blob/main/src/Extension/BaseElementExtension.php#L118-L133
