### ISSUE TITLE
doPublish has been deprecated in Versioned

### ISSUE THREAD

**Issue by lars-lemon8** [dnadesign/silverstripe-elemental-virtual#62]
A bit odd,  but it seems doPublish() has been deprecated.  

I can't seem to find this in the upgrade docs (besides https://docs.silverstripe.org/en/5/changelogs/alpha/5.0.0-alpha1/), but stuff breaks in SS5.1

Refer to https://forum.silverstripe.org/t/the-method-publish-does-not-exist-on-page/7822

I'm getting the "Uncaught BadMethodCallException: Object->__call(): the method 'doPublish' does not exist" when trying to archive a content block. 

In the above thread, Guy advises to use copyVersionToStage() or publishRecursive() instead.

**Comment by wilr** [comment]
Strange they'd remove doPublish() and keep doUnpublish() :) Updated now.
