### ISSUE TITLE
Installing via composer provides no templates? (custom theme)

### ISSUE THREAD

**Issue by muppsy007** [dnadesign/silverstripe-elemental-virtual#7]
Installed via composer and after dev/build and reloading page with a virtual object on it I get this:

> [USER WARNING] NONE OF THE FOLLOWING TEMPLATES COULD BE FOUND: ARRAY ( [0] => DNADESIGN\ELEMENTALVIRTUAL\MODEL\ELEMENTVIRTUAL [1] => DNADESIGN\ELEMENTALVIRTUAL\MODEL\ELEMENTVIRTUAL ) IN THEMES "ARRAY ( [0] => MYTHEME [1] => $DEFAULT ) "

This template doesn't actually seem to exist in the codebase either. Where should we find this?

Theme set via /mysite/_config/theme.yml as follows:

```
---
Name: mytheme
---
SilverStripe\View\SSViewer:
  themes:
    - 'mytheme'
    - '$default'
```

Any idea? I guess I could build that path inside the theme directory but docs don't suggest the need for that, and it would be a rather polluting path. Should this not be in the module template directory?

**Comment by rodwin** [comment]
@muppsy007 Are you able to figure this out? Having the same issue here. Thanks

**Comment by muppsy007** [comment]
@rodwin No. And after a bit of fiddling I found the module to be a bit buggy in general. Sometimes it finds blocks from other pages. Sometimes it doesn't. There doesn't appear to be much pattern to it functioning or not. Plus it appears to be in a completely broken functional state out of the box.

It looks like the module might be on no one's radar. So I abandoned it as unstable/abandonware. I might revisit it when I have more time to dig into the code myself.

**Comment by wilr** [comment]
@muppsy007 @rodwin This module is a bit alpha, it was stripped out of core module a few months ago and is still a work in progress. Not quite ready / tested for production yet. There'll be a tagged release once it's good to go.

**Comment by muppsy007** [comment]
@wilr Thanks mate. Yup assumed as much. I will likely have a bit of a dig into in the next couple weeks so I'll share whatever I find.

**Comment by rodwin** [comment]
Thank you guys for the info and fantastic work in general
